name: Release ibus-bamboo
run-name: ${{ github.actor }} is triggering on GitHub Actions ðŸš€
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  build-test-nix-flake:
    runs-on: ubuntu-latest
    name: Build nix flake package
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - name: Build flake
      run: nix build
    - name: Use flake devShell
      run: nix develop

  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: sudo apt-get update && sudo apt-get install -y make libibus-1.0-dev libx11-dev libxtst-dev libgtk-3-dev osc
      - run: go mod vendor && make test && make build

